name: Terraform Destroy
on:
  workflow_dispatch:

jobs:

  terraform_destroy:
    name: Destroy Arch
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    outputs:
      image_tag: ${{ steps.build-publish.outputs.image_tag }}
      full_image: ${{ steps.build-publish.outputs.full_image }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      
      - name: TF init
        shell: bash
        run: |
          set -eux
          terraform init -upgrade -reconfigure \
            -backend-config='skip_metadata_api_check=true' \
            -backend-config='skip_region_validation=true' \
            -backend-config='skip_credentials_validation=true' 
      
      - name: TF destroy
        shell: bash
        run: |
          set -eux
          terraform destroy \
            -var 'docker_image=025066248951.dkr.ecr.us-east-2.amazonaws.com/py-docker-hello-world:1.0.${{github.run_number}}' \
            -var 'aws_region=${{ vars.AWS_REGION }}' \
            -auto-approve
